karma/shop/views.py
from flask import (
    Blueprint, flash, redirect, g, render_template, request, url_for
)
from werkzeug.exceptions import abort

# from karma.auth.views import login_required
from flask_login import login_required, current_user
from karma import db
from .models import Category, Product, ProductImage, CartItem, Order, Location
import json
from sqlalchemy import desc
bp = Blueprint('shop', __name__)


@bp.route('/')
@login_required
def index():
    products = Product.query.all()
    products.reverse()
    recommended = Product.query.order_by(desc(Product.views)).limit(2)
    return render_template('shop/index.html', products=products, recommended=recommended)

@bp.route('/product/<int:product_id>/')
@login_required
def single_product(product_id):
    product = Product.query.get(product_id)
    product.incrementTimesViewed()
    return render_template('shop/product_single.html', product=product)

@bp.route('/add-to-cart/', methods=('POST',))
@login_required
def addToCart():
    if request.method == 'POST':
        productId = request.form['id']
        quantity = request.form['quantity'] or 1
        item = CartItem(
            product_id = productId,
            quantity = quantity
        )
        result = current_user.addToCart(item)
        if result is True:
            return 'success'
        else: 
            return 'This item is already in the cart. go to cart and increase the quantity'

@bp.route('/cart/', methods=('GET', 'POST'))
@login_required
def cart():
    if request.method == 'GET':
        if not current_user.cart[0].items:
            pass
        else:
            for item in current_user.cart[0].items:
                item.updateTotal()
            current_user.cart[0].updateTotal()
        return render_template('shop/shopping_cart.html', cart_items=current_user.cart[0].items, cart=current_user.cart[0])


@bp.route('/cart/update', methods=('GET', 'POST'))
@login_required
def updateCart():
    if request.method == 'POST':
        id = request.form['id']
        quantity = request.form['quantity']

        item = CartItem.query.get(id)
        item.quantity=quantity
        item.save()
        return 'success'

@bp.route('/checkout/', methods=('GET', 'POST'))
@login_required
def checkout():
    return render_template('shop/checkout.html', order_items=current_user.cart[0].items, cart=current_user.cart[0])

@bp.route('/cart/deleteitem/', methods=('POST', 'GET'))
@login_required
def deleteItemFromCart():
    if request.method == "POST":
        id = request.form['id']
        item = CartItem.query.get(id)
        db.session.delete(item)
        db.session.commit()
        return 'success'

@bp.route('/cart/placeorder/', methods=('POST', ))
@login_required
def placeOrder():
    coords = json.loads(request.form['coords'])
    print(coords)
    location = Location(
        longitude=coords['lng'],
        latitude=coords['lat'],
        country=coords['country'],
        address=coords['address']
    )
    current_user.placeOrder(location)
    return 'success'

@bp.route('/confirmation/', methods=('GET', ))
@login_required
def confirmation():
    return render_template('shop/confirmation.html', order=current_user.orders[-1])

@bp.route('/orders/', methods=('GET',))
@login_required
def viewOrders():
    return render_template('shop/orders.html', orders=current_user.orders)

karma/templates/base.html
<!DOCTYPE html>
<html lang="zxx" class="no-js">

<head>
	<!-- Mobile Specific Meta -->
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<!-- Favicon-->
	<link rel="shortcut icon" href="{{ url_for('static', filename='img/fav.png') }}">
	<!-- Author Meta -->
	<meta name="author" content="CodePixar">
	<!-- Meta Description -->
	<meta name="description" content="">
	<!-- Meta Keyword -->
	<meta name="keywords" content="">
	<!-- meta character set -->
	<meta charset="UTF-8">
	<!-- Site Title -->
	<title>{% block title %}Title{% endblock %}</title>
	<!--
		CSS
		============================================= -->
	<link rel="stylesheet" href="{{ url_for('static', filename='css/linearicons.css') }}">
	<link rel="stylesheet" href="{{ url_for('static', filename='css/font-awesome.min.css') }}">
	<link rel="stylesheet" href="{{ url_for('static', filename='css/themify-icons.css') }}">
	<link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.css') }}">
	<link rel="stylesheet" href="{{ url_for('static', filename='css/owl.carousel.css') }}">
	<link rel="stylesheet" href="{{ url_for('static', filename='css/nice-select.css') }}">
	<link rel="stylesheet" href="{{ url_for('static', filename='css/nouislider.min.css') }}">
	<link rel="stylesheet" href="{{ url_for('static', filename='css/ion.rangeSlider.css') }}" />
	<link rel="stylesheet" href="{{ url_for('static', filename='css/ion.rangeSlider.skinFlat.css') }}" />
	<link rel="stylesheet" href="{{ url_for('static', filename='css/magnific-popup.css') }}">
	<link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}">
	<link rel="stylesheet" href="{{ url_for('static', filename='css/croppie.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/toastr.min.css') }}">
	<style>
		a{
			cursor: pointer;
		}

		@keyframes bounce { 
		0% { transform: translateY(0); }
		100% { transform: translateY(-10px); }
		}
		.bounce {
		animation: bounce 1s;
		animation-direction: alternate;
		animation-iteration-count: infinite;
		}

		.owl-nav{
    	top: 469px;
		}
	</style>
</head>

<body>

	<!-- Start Header Area -->
	{% include 'header.html' %}
    <!-- End Header Area -->
    


	{% block body %}

	{% endblock %}
    
	<!-- start footer Area -->
	{% include 'footer.html' %}
	<!-- End footer Area -->

	<script src="{{ url_for('static', filename='js/vendor/jquery-2.2.4.min.js' ) }}"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4"
	 crossorigin="anonymous"></script>
	<script src="{{ url_for('static', filename='js/vendor/bootstrap.min.js' ) }}"></script>
	<script src="{{ url_for('static', filename='js/jquery.ajaxchimp.min.js' ) }}"></script>
	<script src="{{ url_for('static', filename='js/jquery.nice-select.min.js' ) }}"></script>
	<script src="{{ url_for('static', filename='js/jquery.sticky.js' ) }}"></script>
	<script src="{{ url_for('static', filename='js/nouislider.min.js' ) }}"></script>
	<script src="{{ url_for('static', filename='js/countdown.js' ) }}"></script>
	<script src="{{ url_for('static', filename='js/jquery.magnific-popup.min.js' ) }}"></script>
	<script src="{{ url_for('static', filename='js/owl.carousel.min.js' ) }}"></script>
	<!--gmaps Js-->
	<!-- <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCjCGmQ0Uq4exrzdcL6rvxywDDOvfAu6eE&callback=initMap"></script> -->
	<script src="{{ url_for('static', filename='js/gmaps.min.js' ) }}"></script>
	<script src="{{ url_for('static', filename='js/main.js' ) }}"></script>
	<!-- ui and alerts -->
	<script src="{{ url_for('static', filename='js/sweetalert.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/croppie.min.js') }}"></script>
	<script src="{{ url_for('static', filename='js/toastr.min.js') }}"></script>
	    <script>
            toastr.options = {
        "closeButton": true,
        "debug": false,
        "newestOnTop": false,
        "progressBar": true,
        "positionClass": "toast-top-center",
        "preventDuplicates": true,
        "onclick": null,
        "showDuration": "300",
        "hideDuration": "10",
        "timeOut": "5000",
        "extendedTimeOut": "1000",
        "showEasing": "swing",
        "hideEasing": "linear",
        "showMethod": "fadeIn",
        "hideMethod": "fadeOut"
    }
    </script>
	{% block scripts %}
	
	{% endblock %}
</body>

</html>

karma/templates/footer.html
<footer class="footer-area section_gap">
    <div class="container">
        <div class="row">
            <div class="col-lg-3  col-md-6 col-sm-6">
                <div class="single-footer-widget">
                    <h6>About Us</h6>
                    <p>
                        Karma is an online food shopping website, where users get to make orders for different varieties of food items. 
                        The great thing about us is that our platform is integrated with a smart recommender system that recommends 
                        different food items to it's users based on the user's activities on the platform.
                    </p>
                </div>
            </div>
            <div class="col-lg-4  col-md-6 col-sm-6">
                <div class="single-footer-widget">
                    <h6>Newsletter</h6>
                    <p>Stay update with our latest</p>
                    <div class="" id="mc_embed_signup">

                        <form target="_blank" novalidate="true" action="https://spondonit.us12.list-manage.com/subscribe/post?u=1462626880ade1ac87bd9c93a&amp;id=92a4423d01"
                         method="get" class="form-inline">

                            <div class="d-flex flex-row">

                                <input class="form-control" name="EMAIL" placeholder="Enter Email" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter Email '"
                                 required="" type="email">


                                <button class="click-btn btn btn-default"><i class="fa fa-long-arrow-right" aria-hidden="true"></i></button>
                                <div style="position: absolute; left: -5000px;">
                                    <input name="b_36c4fd991d266f23781ded980_aefe40901a" tabindex="-1" value="" type="text">
                                </div>

                                <!-- <div class="col-lg-4 col-md-4">
                                            <button class="bb-btn btn"><span class="lnr lnr-arrow-right"></span></button>
                                        </div>  -->
                            </div>
                            <div class="info"></div>
                        </form>
                    </div>
                </div>
            </div>
            <div class="col-lg-3  col-md-6 col-sm-6">
                <div class="single-footer-widget mail-chimp">
                    <h6 class="mb-20">Instragram Feed</h6>
                    <ul class="instafeed d-flex flex-wrap">
                        <li><img src="{{url_for('static', filename='img/i1.jpg')}}" alt=""></li>
                        <li><img src="{{url_for('static', filename='img/i2.jpg')}}" alt=""></li>
                        <li><img src="{{url_for('static', filename='img/i3.jpg')}}" alt=""></li>
                        <li><img src="{{url_for('static', filename='img/i4.jpg')}}" alt=""></li>
                        <li><img src="{{url_for('static', filename='img/i5.jpg')}}" alt=""></li>
                        <li><img src="{{url_for('static', filename='img/i6.jpg')}}" alt=""></li>
                        <li><img src="{{url_for('static', filename='img/i7.jpg')}}" alt=""></li>
                        <li><img src="{{url_for('static', filename='img/i8.jpg')}}" alt=""></li>
                    </ul>
                </div>
            </div>
            <div class="col-lg-2 col-md-6 col-sm-6">
                <div class="single-footer-widget">
                    <h6>Follow Us</h6>
                    <p>Let us be social</p>
                    <div class="footer-social d-flex align-items-center">
                        <a href="#"><i class="fa fa-facebook"></i></a>
                        <a href="#"><i class="fa fa-twitter"></i></a>
                        <a href="#"><i class="fa fa-dribbble"></i></a>
                        <a href="#"><i class="fa fa-behance"></i></a>
                    </div>
                </div>
            </div>
        </div>
        <div class="footer-bottom d-flex justify-content-center align-items-center flex-wrap">
            <p class="footer-text m-0"><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This project is made by <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://stakescrypto.com" target="_blank">CPE 500L Students of Computer Engineering</a>
<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
</p>
        </div>
    </div>
</footer>

karma/templates/header.html
<header class="header_area sticky-header">
    <div class="main_menu">
        <nav class="navbar navbar-expand-lg navbar-light main_box">
            <div class="container">
                <!-- Brand and toggle get grouped for better mobile display -->
                <a class="navbar-brand logo_h" href="{{url_for('shop.index')}}">
                    <img src="{{ url_for('static', filename='img/logo.png') }}" alt="">
                    <!-- Logo -->
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                 aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <!-- Collect the nav links, forms, and other content for toggling -->
                <div class="collapse navbar-collapse offset" id="navbarSupportedContent">
                    {% if not current_user.is_anonymous %}
                    <ul class="nav navbar-nav menu_nav ml-auto">
                        
                        
                        
                        <li class="nav-item active"><a class="nav-link" href="{{url_for('shop.index')}}">Home</a></li>
                        <li class="nav-item active"><a class="nav-link" href="{{url_for('shop.viewOrders')}}">Orders</a></li>
                        <li class="nav-item submenu dropdown">
                            <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                             aria-expanded="false">Shop</a>
                            <ul class="dropdown-menu">
                                <!-- <li class="nav-item"><a class="nav-link" href="category.html">Shop Category</a></li>
                                <li class="nav-item"><a class="nav-link" href="single-product.html">Product Details</a></li>
                                <li class="nav-item"><a class="nav-link" href="checkout.html">Product Checkout</a></li> -->
                                <li class="nav-item"><a class="nav-link" href="{{ url_for('shop.cart') }}">Shopping Cart</a></li>
                                <!-- <li class="nav-item"><a class="nav-link" href="confirmation.html">Confirmation</a></li> -->
                            </ul>
                        </li>
                        <!-- <li class="nav-item submenu dropdown">
                            <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                             aria-expanded="false">Blog</a>
                            <ul class="dropdown-menu">
                                <li class="nav-item"><a class="nav-link" href="blog.html">Blog</a></li>
                                <li class="nav-item"><a class="nav-link" href="single-blog.html">Blog Details</a></li>
                            </ul>
                        </li> -->
                        <!-- <li class="nav-item submenu dropdown">
                            <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                             aria-expanded="false">Pages</a>
                            <ul class="dropdown-menu">
                                <li class="nav-item"><a class="nav-link" href="{{ url_for('auth.login') }}">Login</a></li>
                                <li class="nav-item"><a class="nav-link" href="tracking.html">Tracking</a></li>
                                <li class="nav-item"><a class="nav-link" href="elements.html">Elements</a></li>
                            </ul>
                        </li> -->
                        <!-- <li class="nav-item"><a class="nav-link" href="contact.html">Contact</a></li> -->
                        {% if current_user.is_admin %}
                        <li class="nav-item"><a class="nav-link" href="{{url_for('admin.dashboard')}}">Admin</a></li>
                        {% endif %}
                        <li class="nav-item"><a class="nav-link" href="{{url_for('auth.logout')}}">Logout</a></li>
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        <li class="nav-item"><a href="{{url_for('shop.cart')}}" class="cart"><span class="ti-bag"> Cart</span></a></li>
                        <li class="nav-item">
                            <button class="search"><span class="lnr lnr-magnifier" id="search"></span></button>
                        </li>
                    </ul>
                    {% endif %}
                </div>
            </div>
        </nav>
    </div>
    <div class="search_input" id="search_input_box">
        <div class="container">
            <form class="d-flex justify-content-between">
                <input type="text" class="form-control" id="search_input" placeholder="Search Here">
                <button type="submit" class="btn"></button>
                <span class="lnr lnr-cross" id="close_search" title="Close Search"></span>
            </form>
        </div>
    </div>
</header>