karma/shop/models.py
from karma import db
from werkzeug.security import check_password_hash, generate_password_hash
from datetime import datetime
from sqlalchemy.ext.hybrid import hybrid_property
# from karma.auth.models import User
from datetime import datetime
from flask_login import current_user
from datetime import datetime


class HasImage:
    def storeImage(self):
        pass

    def deleteImage(self):
        pass


class SavableMixin:
    def save(self):
        db.session.add(self)
        db.session.commit()


class Category(db.Model, HasImage):
    category_id = db.Column(
        db.Integer,
        primary_key=True,
        nullable=False,
        autoincrement=True
    )

    name = db.Column(
        db.String(100),
        nullable=False,
        unique=True
    )

    image = db.Column(
        db.String(100),
        nullable=False,
        unique=True
    )

    # products = db.relationship('Product', backref=db.backref('category', lazy=True))

    def deleteImage(self):
        from karma.admin.views import Image, CATEGORY_URL, PRODUCT_URL
        image = Image(None, CATEGORY_URL, self.image)
        image.deleteImage()

    def storeImage(self, image):
        from karma.admin.views import Image, CATEGORY_URL, PRODUCT_URL
        image = Image(image, CATEGORY_URL)
        self.image = image.create()


class Product(db.Model):
    product_id = db.Column(
        db.Integer,
        primary_key=True,
        nullable=False,
        autoincrement=True
    )
    title = db.Column(
        db.String(100)
    )
    description = db.Column(
        db.String(500),
        nullable=True
    )
    price = db.Column(
        db.Float,
        nullable=False,
        default=0.00
    )
    times_bought = db.Column(
        db.Integer,
        nullable=False,
        default=0
    )
    views = db.Column(
        db.Integer,
        nullable= False,
        default = 0
    )
    in_stock = db.Column(
        db.Integer,
        nullable=False,
        default=3
    )
    category_id = db.Column(
        db.Integer,
        db.ForeignKey('category.category_id'),
        nullable=False
    )
    
    # images = db.relationship('ProductImage', backref=db.backref('product', lazy=True))
    category = db.relationship(
        'Category', backref=db.backref('product', lazy=True))

    def addImages(self, images):
        for image in images:
            image_name = self.storeImage(image)
            img = ProductImage(name=image_name)
            self.images.append(img)

    def storeImage(self, image):
        from karma.admin.views import Image, CATEGORY_URL, PRODUCT_URL
        image = Image(image, PRODUCT_URL)
        return image.create()

    def delete(self,):
        self.deleteImages()
        db.session.delete(self)
        db.session.commit()

    def deleteImages(self,):
        for image in self.images:
            image.delete()
        return True
    
    def incrementTimesViewed(self):
        self.views+=1
        db.session.add(self)
        db.session.commit()

    def incrementTimesBought(self, quantity = 1):
        self.times_bought+=quantity
        db.session.add(self)
        db.session.commit()


class ProductImage(db.Model):
    image_id = db.Column(
        db.Integer,
        primary_key=True,
        nullable=False,
        autoincrement=True
    )

    product_id = db.Column(
        db.Integer,
        db.ForeignKey('product.product_id'),
        nullable=False
    )

    name = db.Column(
        db.String(100)
    )

    product = db.relationship(
        'Product',
        backref=db.backref('images', lazy=True),
    )

    def delete(self):
        from karma.admin.views import Image, CATEGORY_URL, PRODUCT_URL
        image = Image(None, PRODUCT_URL, self.name)
        image.deleteImage()
        db.session.delete(self)


OrderStatus = {
    'PENDING': 'pending',
    'CLOSED': 'closed',
    'TRANSIT': 'transit',
    'DELIVERED': 'delivered'
}

class Order(db.Model):
    order_id = db.Column(
        db.Integer,
        primary_key=True,
        nullable=False,
        autoincrement=True
    )

    status = db.Column(
        db.String(15),
        nullable=False,
        default=OrderStatus['PENDING']
    )

    date_created = db.Column(
        db.DateTime,
        nullable=False,
        default=datetime.now
    )

    user_id = db.Column(
        db.Integer,
        db.ForeignKey('user.user_id'),
        nullable=False
    )

    user = db.relationship(
        'User',
        backref=db.backref('orders', lazy=True)
    )

    total = db.Column(
        db.Float,
        nullable=False,
        default=0.00
    )

    @staticmethod
    def count():
        return len(Order.query.all())

    @staticmethod
    def pendingOrders():
        return len(Order.query.filter_by(status=OrderStatus['PENDING']).all())

    @staticmethod
    def deliveredOrders():
        return len(Order.query.filter_by(status=OrderStatus['DELIVERED']).all())

    @staticmethod
    def transitOrders():
        return len(Order.query.filter_by(status=OrderStatus['TRANSIT']).all())

    def setLocation(self, location):
        self.location.append(location)

    def setUpItems(self, ):
        for item in current_user.cart[0].items:
            newItem = OrderItem(
                product_id=item.product_id,
                quantity=item.quantity,
                total=item.total
            )
            item.product.incrementTimesBought(item.quantity)
            self.orderitems.append(newItem)
            self.updateTotal()

    def updateTotal(self):
        self.total = current_user.cart[0].total


class OrderItem(db.Model):
    order_item_id = db.Column(
        db.Integer,
        primary_key=True,
        nullable=False,
        autoincrement=True
    )

    order_id = db.Column(
        db.Integer,
        db.ForeignKey('order.order_id'),
        nullable=False
    )

    order = db.relationship(
        'Order',
        backref=db.backref('orderitems', lazy=True)
    )

    product_id = db.Column(
        db.Integer,
        db.ForeignKey('product.product_id'),
        nullable=False,
    )

    product = db.relationship(
        'Product',
        uselist=False
    )

    quantity = db.Column(
        db.Integer,
        nullable=False,
        default=1,
    )

    total = db.Column(
        db.Float,
        nullable=False,
        default=0.00
    )

    def calculateTotal(self):
        return self.product.price*self.quantity

    def updateTotal(self):
        self.total = self.calculateTotal()
        self.save()
        return True


class Cart(db.Model, SavableMixin):

    def __init__(self, **kwargs):
        super(Cart, self).__init__(**kwargs)
        self.updateTotal()
        print('cart created')

    cart_id = db.Column(
        db.Integer,
        primary_key=True,
        nullable=False,
        autoincrement=True
    )

    user_id = db.Column(
        db.Integer,
        db.ForeignKey('user.user_id'),
        nullable=False,
    )

    user = db.relationship(
        'User',
        backref='cart',
        uselist=True,
    )

    total = db.Column(
        db.Float,
        nullable=False,
        default=0.00
    )

    def itemExists(self, item):
        for product in self.items:
            if str(product.product_id) == str(item.product_id):
                return True
        return False

    def retrieveItem(self, item):
        for product in self.items:
            if str(product.product_id) == str(item.product_id):
                return product

    def addItem(self, item):
        if(self.itemExists(item)):
            existingItem = self.retrieveItem(item)
            existingItem.quantity = int(
                existingItem.quantity) + int(item.quantity)
            print(
                """
                This item already exists
                """
            )
        else:
            self.items.append(item)
        self.save()
        return True

    def calculateTotal(self):
        total = 0
        for item in self.items:
            total += item.total
        return total

    def updateTotal(self):
        self.total = self.calculateTotal()
        self.save()
        return True

    def clear(self):
        self.total = 0
        for item in self.items:
            item.delete()
        self.save()


class CartItem(db.Model, SavableMixin):

    def __init__(self, **kwargs):
        super(CartItem, self).__init__(**kwargs)
        # self.updateTotal()
        # print('cart item created')

    cart_item_id = db.Column(
        db.Integer,
        primary_key=True,
        nullable=False,
        autoincrement=True
    )

    cart_id = db.Column(
        db.Integer,
        db.ForeignKey('cart.cart_id'),
        nullable=False
    )

    product_id = db.Column(
        db.Integer,
        db.ForeignKey('product.product_id'),
        nullable=False
    )

    product = db.relationship(
        'Product',
        uselist=False
    )

    cart = db.relationship(
        'Cart',
        backref=db.backref('items', lazy=True)
    )

    quantity = db.Column(
        db.Integer,
        nullable=False,
        default=1
    )

    total = db.Column(
        db.Float,
        nullable=False,
        default=0,
    )

    def calculateTotal(self):
        return self.product.price*self.quantity

    def updateTotal(self):
        self.total = self.calculateTotal()
        self.save()
        return True

    def delete(self):
        db.session.delete(self)


class Location(db.Model):
    location_id = db.Column(
        db.Integer,
        primary_key=True,
        nullable=False,
        autoincrement=True
    )

    order_id = db.Column(
        db.Integer,
        db.ForeignKey('order.order_id'),
        nullable=False
    )

    latitude = db.Column(
        db.Float,
        nullable=False,
    )

    longitude = db.Column(
        db.Float,
        nullable=False
    )

    country = db.Column(
        db.String(200),
        nullable=True
    )

karma/shop/__init__.py
from .views import bp

karma/shop/views.py
from flask import (
    Blueprint, flash, redirect, g, render_template, request, url_for
)
from werkzeug.exceptions import abort

# from karma.auth.views import login_required
from flask_login import login_required, current_user
from karma import db
from .models import Category, Product, ProductImage, CartItem, Order, Location
import json
from sqlalchemy import desc
bp = Blueprint('shop', __name__)


@bp.route('/')
@login_required
def index():
    products = Product.query.all()
    products.reverse()
    recommended = Product.query.order_by(desc(Product.views)).limit(2)
    return render_template('shop/index.html', products=products, recommended=recommended)

@bp.route('/product/<int:product_id>/')
@login_required
def single_product(product_id):
    product = Product.query.get(product_id)
    product.incrementTimesViewed()
    return render_template('shop/product_single.html', product=product)

@bp.route('/add-to-cart/', methods=('POST',))
@login_required
def addToCart():
    if request.method == 'POST':
        productId = request.form['id']
        quantity = request.form['quantity'] or 1
        item = CartItem(
            product_id = productId,
            quantity = quantity
        )
        result = current_user.addToCart(item)
        if result is True:
            return 'success'
        else: 
            return 'This item is already in the cart. go to cart and increase the quantity'

@bp.route('/cart/', methods=('GET', 'POST'))
@login_required
def cart():
    if request.method == 'GET':
        if not current_user.cart[0].items:
            pass
        else:
            for item in current_user.cart[0].items:
                item.updateTotal()
            current_user.cart[0].updateTotal()
        return render_template('shop/shopping_cart.html', cart_items=current_user.cart[0].items, cart=current_user.cart[0])


@bp.route('/cart/update', methods=('GET', 'POST'))
@login_required
def updateCart():
    if request.method == 'POST':
        id = request.form['id']
        quantity = request.form['quantity']

        item = CartItem.query.get(id)
        item.quantity=quantity
        item.save()
        return 'success'

@bp.route('/checkout/', methods=('GET', 'POST'))
@login_required
def checkout():
    return render_template('shop/checkout.html', order_items=current_user.cart[0].items, cart=current_user.cart[0])

@bp.route('/cart/deleteitem/', methods=('POST', 'GET'))
@login_required
def deleteItemFromCart():
    if request.method == "POST":
        id = request.form['id']
        item = CartItem.query.get(id)
        db.session.delete(item)
        db.session.commit()
        return 'success'

@bp.route('/cart/placeorder/', methods=('POST', ))
@login_required
def placeOrder():
    coords = json.loads(request.form['coords'])
    print(coords)
    location = Location(
        longitude=coords['lng'],
        latitude=coords['lat'],
        country=coords['country'],
        address=coords['address']
    )
    current_user.placeOrder(location)
    return 'success'

@bp.route('/confirmation/', methods=('GET', ))
@login_required
def confirmation():
    return render_template('shop/confirmation.html', order=current_user.orders[-1])

@bp.route('/orders/', methods=('GET',))
@login_required
def viewOrders():
    return render_template('shop/orders.html', orders=current_user.orders)

karma/templates/shop/branded_area.html
<section class="brand-area section_gap">
    <div class="container">
        <div class="row">
            <a class="col single-img" href="#">
                <img class="img-fluid d-block mx-auto" src="{{ url_for('static', filename='img/brand/1.png') }}" alt="">
            </a>
            <a class="col single-img" href="#">
                <img class="img-fluid d-block mx-auto" src="{{ url_for('static', filename='img/brand/2.png') }}" alt="">
            </a>
            <a class="col single-img" href="#">
                <img class="img-fluid d-block mx-auto" src="{{ url_for('static', filename='img/brand/3.png') }}" alt="">
            </a>
            <a class="col single-img" href="#">
                <img class="img-fluid d-block mx-auto" src="{{ url_for('static', filename='img/brand/4.png') }}" alt="">
            </a>
            <a class="col single-img" href="#">
                <img class="img-fluid d-block mx-auto" src="{{ url_for('static', filename='img/brand/5.png') }}" alt="">
            </a>
        </div>
    </div>
</section>

karma/templates/shop/category_area.html
<section class="category-area">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-8 col-md-12">
                <div class="row">
                    <div class="col-lg-8 col-md-8">
                        <div class="single-deal">
                            <div class="overlay"></div>
                            <img class="img-fluid w-100" src="{{ url_for('static', filename='img/category/c1.jpg') }}" alt="">
                            <a href="{{ url_for('static', filename='img/category/c1.jpg') }}" class="img-pop-up" target="_blank">
                                <div class="deal-details">
                                    <h6 class="deal-title">Sneaker for Sports</h6>
                                </div>
                            </a>
                        </div>
                    </div>
                    <div class="col-lg-4 col-md-4">
                        <div class="single-deal">
                            <div class="overlay"></div>
                            <img class="img-fluid w-100" src="{{ url_for('static', filename='img/category/c2.jpg') }}" alt="">
                            <a href="{{ url_for('static', filename='img/category/c2.jpg') }}" class="img-pop-up" target="_blank">
                                <div class="deal-details">
                                    <h6 class="deal-title">Sneaker for Sports</h6>
                                </div>
                            </a>
                        </div>
                    </div>
                    <div class="col-lg-4 col-md-4">
                        <div class="single-deal">
                            <div class="overlay"></div>
                            <img class="img-fluid w-100" src="{{ url_for('static', filename='img/category/c3.jpg') }}" alt="">
                            <a href="{{ url_for('static', filename='img/category/c3.jpg') }}" class="img-pop-up" target="_blank">
                                <div class="deal-details">
                                    <h6 class="deal-title">Product for Couple</h6>
                                </div>
                            </a>
                        </div>
                    </div>
                    <div class="col-lg-8 col-md-8">
                        <div class="single-deal">
                            <div class="overlay"></div>
                            <img class="img-fluid w-100" src="{{ url_for('static', filename='img/category/c4.jpg') }}" alt="">
                            <a href="{{ url_for('static', filename='img/category/c4.jpg') }}" class="img-pop-up" target="_blank">
                                <div class="deal-details">
                                    <h6 class="deal-title">Sneaker for Sports</h6>
                                </div>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-4 col-md-6">
                <div class="single-deal">
                    <div class="overlay"></div>
                    <img class="img-fluid w-100" src="{{url_for('static', filename='img/category/c5.jpg')}}" alt="">
                    <a href="{{url_for('static', filename='img/category/c5.jpg')}}" class="img-pop-up" target="_blank">
                        <div class="deal-details">
                            <h6 class="deal-title">Sneaker for Sports</h6>
                        </div>
                    </a>
                </div>
            </div>
        </div>
    </div>
</section>

karma/templates/shop/confirmation.html
{% extends 'base.html'%}
{% block title %}Karma Shop{% endblock %}

{% block body%}

	<!-- Start Banner Area -->
	<section class="banner-area organic-breadcrumb">
		<div class="container">
			<div class="breadcrumb-banner d-flex flex-wrap align-items-center justify-content-end">
				<div class="col-first">
					<h1>Confirmation</h1>
					<nav class="d-flex align-items-center">
						<a href="index.html">Home<span class="lnr lnr-arrow-right"></span></a>
						<a href="category.html">Confirmation</a>
					</nav>
				</div>
			</div>
		</div>
	</section>
	<!-- End Banner Area -->

	<!--================Order Details Area =================-->
	<section class="order_details section_gap">
		<div class="container">
			<h3 class="title_confirmation">Thank you. Your order has been received, You will be contacted by an agent soon.</h3>
			<div class="row order_d_inner">
				<div class="col-lg-4">
					<div class="details_item">
						<h4>Order Info</h4>
						<ul class="list">
							<li><a href="#"><span>Order number</span> : {{order.order_id}}</a></li>
							<li><a href="#"><span>Date</span> : {{order.date_created}}</a></li>
							<li><a href="#"><span>Total</span> :₦{{order.total}} </a></li>
							<li><a href="#"><span>Payment method</span> : Cash</a></li>
						</ul>
					</div>
				</div>
				<!-- <div class="col-lg-4">
					<div class="details_item">
						<h4>Billing Address</h4>
						<ul class="list">
							<li><a href="#"><span>Street</span> : 56/8</a></li>
							<li><a href="#"><span>City</span> : Los Angeles</a></li>
							<li><a href="#"><span>Country</span> : United States</a></li>
							<li><a href="#"><span>Postcode </span> : 36952</a></li>
						</ul>
					</div>
				</div> -->
				<div class="col-lg-8">
					<div class="details_item">
						<h4>Shipping Address</h4>
						<ul class="list">
							<li><a href="#"><span>address</span>: {{order.location[0].address}}</a></li>
							<!-- <li><a href="#"><span>City</span> : Los Angeles</a></li> -->
							<li><a href="#"><span>Country</span>: {{order.location[0].country}}</a></li>
							<!-- <li><a href="#"><span>Postcode </span> : 36952</a></li> -->
						</ul>
					</div>
				</div>
			</div>
			<div class="order_details_table">
				<h2>Order Details</h2>
				<div class="table-responsive">
					<table class="table">
						<thead>
							<tr>
								<th scope="col">Product</th>
								<th scope="col">Quantity</th>
								<th scope="col">Total</th>
							</tr>
						</thead>
						<tbody>
                            {% for item in order.orderitems %}
                            <tr>
								<td>
									<p>{{item.product.title}}</p>
								</td>
								<td>
									<h5>x {{item.quantity}}</h5>
								</td>
								<td>
									<p>₦{{item.total}}</p>
								</td>
							</tr>
                            {% endfor %}
							<tr>
								<td>
									<h4>Subtotal</h4>
								</td>
								<td>
									<h5></h5>
								</td>
								<td>
									<p>₦{{order.total}}</p>
								</td>
							</tr>
							<tr>
								<td>
									<h4>Shipping</h4>
								</td>
								<td>
									<h5></h5>
								</td>
								<td>
									<p>Flat rate: ₦200</p>
								</td>
							</tr>
							<tr>
								<td>
									<h4>Total</h4>
								</td>
								<td>
									<h5></h5>
								</td>
								<td>
									<p>₦{{order.total+200}}</p>
								</td>
							</tr>
						</tbody>
					</table>
				</div>
			</div>
		</div>
	</section>
	<!--================End Order Details Area =================-->


{% endblock %}

{% block scripts %}

{% endblock %}

karma/templates/shop/index.html
{% extends 'base.html'%}
{% block title %}Karma Shop{% endblock %}

{% block body%}

	<!-- start banner Area -->
	<section class="banner-area">
		<div class="container">
			<div class="row fullscreen align-items-center justify-content-start">
				<div class="col-lg-12">
					<div class="active-banner-slider owl-carousel">
						<!-- single-slide -->
						<div class="row single-slide align-items-center d-flex">
							<div class="col-lg-5 col-md-6">
								<div class="banner-content mt-5">
									<h1>Place your orders from anywhere! <br></h1>
									<p>Get any order you make within 30 minutes of making the order! We are reliable, fast and
										efficient and guarantee your orders 100% safety.
									</p>
									<!-- <div class="add-bag d-flex align-items-center">
										<a class="add-btn" href=""><span class="lnr lnr-cross"></span></a>
										<span class="add-text text-uppercase">Add to Bag</span>
									</div> -->
								</div>
							</div>
							<div class="col-lg-7">
								<div class="banner-img bounce" style="margin-top: 100px;">
									<img class="img-fluid" src="{{url_for('static', filename='img/banner/Food-Free-PNG-Image.png')}}" alt="">
								</div>
							</div>
						</div>
						<!-- single-slide -->
						<div class="row single-slide">
							<div class="col-lg-5">
								<div class="banner-content mt-5">
									<h1>Anytime,  <br> Anywhere!</h1>
									<p>Our responses are quick and precise.</p>
									<!-- <div class="add-bag d-flex align-items-center">
										<a class="add-btn" href=""><span class="lnr lnr-cross"></span></a>
										<span class="add-text text-uppercase">Add to Bag</span>
									</div> -->
								</div>
							</div>
							<div class="col-lg-7">
								<div class="banner-img bounce" style="margin-top: 100px;">
									<img class="img-fluid" src="{{url_for('static', filename='img/banner/Food-Free-Download-PNG.png')}}" alt="">
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</section>
	<!-- End banner Area -->

	<!-- start features Area -->
	<section class="features-area section_gap bounce">
		<div class="container">
			<div class="row features-inner">
				<!-- single features -->
				<div class="col-lg-3 col-md-6 col-sm-6">
					<div class="single-features">
						<div class="f-icon">
							<img src="{{url_for('static', filename='img/features/f-icon1.png')}}" alt="">
						</div>
						<h6>Quick Delivery</h6>
						<p>Free Shipping on all order</p>
					</div>
				</div>
				<!-- single features -->
				<div class="col-lg-3 col-md-6 col-sm-6">
					<div class="single-features">
						<div class="f-icon">
							<img src="{{url_for('static', filename='img/features/f-icon2.png')}}" alt="">
						</div>
						<h6>Return Policy</h6>
						<p>quick returns on faulty orders</p>
					</div>
				</div>
				<!-- single features -->
				<div class="col-lg-3 col-md-6 col-sm-6">
					<div class="single-features">
						<div class="f-icon">
							<img src="{{url_for('static', filename='img/features/f-icon3.png')}}" alt="">
						</div>
						<h6>24/7 Support</h6>
						<p>Receive constant feedback from our support agents</p>
					</div>
				</div>
				<!-- single features -->
				<div class="col-lg-3 col-md-6 col-sm-6">
					<div class="single-features">
						<div class="f-icon">
							<img src="{{url_for('static', filename='img/features/f-icon4.png')}}" alt="">
						</div>
						<h6>Secure Payment</h6>
						<p>Full payment integration for swift payments</p>
					</div>
				</div>
			</div>
		</div>
	</section>
	<!-- end features Area -->

	<!-- Start category Area -->
	 <!-- include 'shop/category_area.html'  -->
	<!-- End category Area -->

	<!-- start product Area -->
	{% include 'shop/latest_products.html' %}
	<!-- end product Area -->

	<!-- Start exclusive deal Area -->
	 <!-- include 'shop/exclusivedeal_area.html'  -->
	<!-- End exclusive deal Area -->

	<!-- Start brand Area -->
	{% include 'shop/branded_area.html' %}
	<!-- End brand Area -->

	<!-- Start related-product Area -->
	<!-- {% include 'shop/dealsoftheweek_area.html' %} -->
	<!-- End related-product Area -->

{% endblock %}


{% block scripts %}
<script>
    // $('.add-to-cart-button').click(function(){
    // 	alert('you want to add a product to cart');
    // });

    $('.add-to-cart-button').on('click', function (img) {
        let productId = $(this).attr('id');
        let datatopost = [];
        datatopost.push({name: 'product', value: 1});
        datatopost.push({name: 'id', value: productId});
        datatopost.push({name: 'quantity', value: 1});
        console.log(datatopost);

        $.ajax({
        url: "{{ url_for('shop.addToCart') }}",
        type: "POST",
        data: datatopost,
        beforeSend:function(){
            toastr.clear();
            toastr.info('Adding to cart');

        },
        success: function (data) {
            if(data == 'success'){
            toastr.clear();
            toastr.success('Item added to cart');
            
            }else{
                swal('Unsuccessful!', data, 'error');
            }
        },
        error: function(){
            toastr.clear();
            swal('Unsuccessful!', 'Please check your network connection', 'error');

        }
        });
    });
</script>
{% endblock %}

karma/templates/shop/latest_products.html
<section class="owl-carousel active-product-area section_gap">
    <!-- single product slide -->
    <div class="single-product-slider">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-6 text-center">
                    <div class="section-title">
                        <h1>All Procucts</h1>
                        <p>This is a list of all the products in the shop</p>
                    </div>
                </div>
            </div>
            <div class="row">
                {% for product in products %}
                                    <!-- single product -->
                                    <div class="col-lg-3 col-md-6">
                                        <div class="single-product">
                                            <img class="img-fluid" src="{{ url_for('static', filename='productuploads/'+product.images[0].name) }}" alt="">
                                            <div class="product-details">
                                                <h6>{{product.title}}</h6>
                                                <div class="price">
                                                    <h6>${{product.price}}</h6>
                                                    <h6 class="l-through">${{product.price+product.price*0.1}}</h6>
                                                </div>
                                                <div class="prd-bottom">
                
                                                    <a class="add-to-cart-button social-info" id="{{ product.product_id }}">
                                                        <span class="ti-bag"></span>
                                                        <p class="hover-text">add to bag</p>
                                                    </a>
                                                    <a href="{{url_for('shop.single_product', product_id=product.product_id)}}" class="social-info">
                                                        <span class="lnr lnr-move"></span>
                                                        <p class="hover-text">view more</p>
                                                    </a>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                {% endfor %}

            </div>
        </div>
    </div>
    <!-- single product slide -->
    <div class="single-product-slider">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-6 text-center">
                    <div class="section-title">
                        <h1>Recommended Products</h1>
                        <p>These are products specially recommended for you based on the general popularity on the platform</p>
                    </div>
                </div>
            </div>
            <div class="row">
                {% for product in recommended %}
                <!-- single product -->
                <div class="col-lg-3 col-md-6">
                    <div class="single-product">
                        <img class="img-fluid" src="{{ url_for('static', filename='productuploads/'+product.images[0].name) }}" alt="">
                        <div class="product-details">
                            <h6>{{product.title}}</h6>
                            <div class="price">
                                <h6>${{product.price}}</h6>
                                <h6 class="l-through">${{product.price+product.price*0.1}}</h6>
                            </div>
                            <div class="prd-bottom">

                                <a class="add-to-cart-button social-info" id="{{ product.product_id }}">
                                    <span class="ti-bag"></span>
                                    <p class="hover-text">add to bag</p>
                                </a>
                                <a href="{{url_for('shop.single_product', product_id=product.product_id)}}" class="social-info">
                                    <span class="lnr lnr-move"></span>
                                    <p class="hover-text">view more</p>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
{% endfor %}
            </div>
        </div>
    </div>
</section>